### ISSUE TITLE
les labels des icônes ne sont pas séparés, on a l'impression que c'est un texte continu

### ISSUE THREAD

**Issue by TANK2003** [data-osm/frontend#10]
#8
![data-osm](https://user-images.githubusercontent.com/11553211/95564056-87e28c80-0a1e-11eb-8941-401811dac43f.png)

- [x] Augmenter la largeur du bandeau gauche

- [x] Augmenter l'intervalle entre les textes

**Comment by overflorian** [comment]
à noter qu'il est également envisageable d'adopter d'autres approches : listes, barre de recherche, .... ou des combiner plusieurs de ces approches

**Comment by TANK2003** [comment]
Bonjour, 
Alors je me suis servi de ce [lien](https://material.io/components/lists#anatomy) du material  pour faire des tests. 
je te mets une  capture de ce qui me parait deja pas mal, mais je continue de penser qu'on peut mieux faire !

<img width="502" alt="Screenshot 2020-10-13 at 21 47 59" src="https://user-images.githubusercontent.com/49986468/95908807-d89b1200-0d9d-11eb-87a2-3ecaf8202217.png">


**NB :** les icônes n'avaient pas été  fait pour le circulaire, ils seront refait si on choisit cette entrée.

Deja la, les textes sont bien plus lisible, les couleurs s'alternent mieux !

tu peux me dire si ca te parle ou si tu veux une demo sur un lien de dev stp ?

Merci encore,

**Comment by overflorian** [comment]
C'est une option possible, mais il y en a aussi plein d'autres : https://github.com/osmontrouge/caresteouvert/issues/225

**Comment by yannickherve** [comment]
On a finalement opté pour le design ci-dessous.
On continue la réflexion pour le design des couches.

Merci.

![commit](https://user-images.githubusercontent.com/49309269/96038200-1879fc00-0e67-11eb-869c-a848419f35a3.png)

**Comment by TANK2003** [comment]
Augment la police et le gras des sous categories

Améliorer la police des infobulles des couches (fond blancs, police >=12), mettre a droite également la tooltip.

Agrandir les logos des couches (35*35px). (Faire un test avec les logos carrés pour tester)

**Comment by TANK2003** [comment]
Dernière version d’amélioration du panneau gauche. C'est en ligne.
@overflorian , tu as encore d'autres suggestions pour ce panneau gauche ? Perso je le trouve bien. 
Dit moi si t'as des choses qui te pique l’œil, si non on peut fermer ce ticket

Merci pour ta disponibilité 
<img width="555" alt="Screenshot 2020-10-18 at 20 01 09" src="https://user-images.githubusercontent.com/49986468/96376042-f93be100-117c-11eb-88a2-f4086cbe4dc7.png">

**Comment by overflorian** [comment]
C'est beaucoup mieux, bravo ! 

Je suggère de trouver UNIQUEMENT des labels assez courts pour être affichés en entier. Par exemple "agences immobilières" deviendrait "Immobilier"

Les couleurs sont beaucoup plus douces, moins agressives, c'est top. Par contre pour certaines couleurs claires, le logo affiché par dessus ne devrait pas apparaître en blanc mais en noir, question de lisibilité.

**Comment by TANK2003** [comment]
Yes, on a réfléchi pour ses noms, à terme on ferra des short name comme dans OSM. Pour l’instant on va essayer de raccourcir les noms au max

C'est noté pour les icônes.

Merci pour ta bienveillance, je ferme donc ce ticket .
