### ISSUE TITLE
Lien de téléchargement cassé pour les données de type route

### ISSUE THREAD

**Issue by pascalpvk** [data-osm/frontend#103]
Bonjour,

J'ai téléchargé sans problème la couche des pistes cyclables. Cependant, en suivant exactement les mêmes étapes, le téléchargement de couches de type Route (Route à 80km/h, Route à 90km/h, Route ...) est cassé.
A noter que lorsque l'on clic sur le i pour faire apparaitre les métadonnées, ainsi que le bouton de téléchargement, le message d'erreur suivant s'affiche systématiquement: "An error occured while loading metadata"

![OSMdata](https://user-images.githubusercontent.com/5699220/164984994-bb0c5ed6-1d29-40a2-8161-b3ad0f8f5e29.png)
"

On peut télécharger un shapefile, mais il est vide et les autres formats font afficher une page d'erreur

https://ws.dataosm.info/api/group/download/?provider_vector_id=undefined&table_id=undefined&provider_style_id_target=327&provider_vector_id_target=328&driver=gpkg

<h1>AttributeError
       at /api/group/download/</h1>
  <pre class="exception_value">'NoneType' object has no attribute 'CopyLayer'</pre>
  

Request Method: | GET
-- | --
http://localhost:9000/api/group/download/?provider_vector_id=undefined&table_id=undefined&provider_style_id_target=327&provider_vector_id_target=328&driver=gpkg
3.2.12
AttributeError
'NoneType' object has no attribute 'CopyLayer'
/code/group/subViews/downloads.py, line 296, in get
/usr/bin/python3
3.7.3
['/code',  '/usr/local/bin',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/usr/lib/python3/dist-packages']
Sun, 24 Apr 2022 15:55:01 +0000

**Comment by TANK2003** [comment]
Merci pour ce retour très détaillé, je regarde ça ce soir.

**Comment by TANK2003** [comment]
Cela a été fixed. Le problème venait du fait qu'il y'avait un '/' dans le nom du fichier en sortie, et cassait tout le code (car il donnait alors un chemin vers le fichier qui était faux)

Pour les métadonnées c'est tout a fait normal, les métadonnées de la grande majorité des couches ne sont pas remplies.
