### ISSUE TITLE
Impossibilité de saisir une emprise

### ISSUE THREAD

**Issue by nodepalkia** [data-osm/frontend#116]
Bonjour,

Depuis plusieurs jours, il m'est impossible de saisir une emprise dans la catégorie "téléchargement de données", ici plus précisément dans la couche "arrêts de bus". Il n'y a plus aucune proposition, aussi bien pour des grandes villes (Lyon) que des communes ou communautés de communes/agglomération. De même, lorsque nous cherchons des villes dans la barre de recherche, ils sont affichés comme des points et non comme des surfaces, et les communautés de communes ne sont pas affichées.

Est-ce que c'est normal ?
Merci d'avance pour votre réponse.

**Comment by TANK2003** [comment]
Merci pour le bug signalé , c'est tout réglé

**Comment by AF02** [comment]
Bonjour, 
 j'ai le même soucis aujourd'hui ; 
Impossible de saisir une emprise dans téléchargement de données. Il n 'y a pas de proposition ni de validation. 
Je en sais pas si le bug est revenu ou si il s 'agit d'un nouveau soucis 
Merci 
Cordialement
