### ISSUE TITLE
diminution de contraste en cas d'affichage de couche

### ISSUE THREAD

**Issue by JLZIMMERMANN** [data-osm/frontend#26]
Dans le cas où une couche est appelée, un réglage à défaut pour les couche se fait avec un contraste diminué de moitié.
![image](https://user-images.githubusercontent.com/4929752/98405124-03f6e100-206c-11eb-875c-373eafb5f113.png)

**Comment by TANK2003** [comment]
je me demande si ca ne troublera pas plus tôt  l'utilisateur ? Il devra comprendre que la couche de base a pris en transparence.
