### ISSUE TITLE
Parkings le long des rues

### ISSUE THREAD

**Issue by tdelmas** [data-osm/frontend#27]
L'affichage des parkings dans la rue "Voirie, parking" est très léger, à peine visible.

Envisager un affichage plus visible et séparant chaque coté de la voie, style https://zlant.github.io/parking-lanes/#18/52.48275/13.43426 ? Ou une option pour changer la taille du trait ?

**Comment by TANK2003** [comment]
Pour ce faire, il faudrait avoir la requête SQL permettant de récupérer les parkings. Dans le [GitHub](https://github.com/zlant/parking-lanes/blob/master/planes.js#L568) de ce projet, la requête est sous Overpass que je maitrise pas bien. Je suis preneur de la requête transformée, ensuite on pourra faire un style QGIS pour obtenir beau résultat.

Merci pour le retour
