### ISSUE TITLE
maison de retraites

### ISSUE THREAD

**Issue by zorglubu** [data-osm/frontend#4]
Les maisons de retraite affichées, correspondent actuellement au tag amenity=nursing_home, qui est une étiquette obsolète : https://wiki.openstreetmap.org/wiki/Nursing_home

Or les maisons de retraites correctement saisies correspondent au wiki : https://wiki.openstreetmap.org/wiki/FR:Comment_cartographier_un_(sant%C3%A9)#EHPAD.2C_EHPA_et_R.C3.A9sidences_Autonomie
c'est-à-dire aux tags       social_facility=nursing_home, group_home ou assisted_living
avec en même temps     social_facility:for=senior
Ce sont celles-ci qu'il faudrait afficher (il y en a près de 6000). Merci.

**Comment by JLZIMMERMANN** [comment]
Voici la requête sur l'interface admin :
amenity='social_facility' AND tags->'social_facility:for'='senior' AND tags->'social_facility' in ('nursing_home','group_home','assisted_living')

celle-ci est déjà en ligne (8636 entités) ici http://demo.openstreetmap.fr//map?layers=couche,490,36

**Comment by zorglubu** [comment]
Ah oui. C'est beaucoup mieux :-)
Juste une remarque, l'entrée a disparu du menu, mais je présume que ça va revenir ?
Merci pour le boulot.

**Comment by TANK2003** [comment]
Bonjour, il s'agit de quelle entrée ? je comprends pas
Merci du temps passé

**Comment by JLZIMMERMANN** [comment]
Je pense qu'il fait allusion au panneau de gauche qui reste générique sans préciser la thématique concernée.

**Comment by zorglubu** [comment]
Oui, c'est cela.
Sauf erreur, dans la rubrique Santé du panneau de gauche, on trouve les "services sociaux" mais pas les "maisons de retraite" correspondant à cet URL http://demo.openstreetmap.fr//map?layers=couche,490,36

**Comment by TANK2003** [comment]
J'ai fait en sorte que le panneau de gauche s'ouvre lors de l'ouverture d'une couche. La fonction sera visible en fin de semaine

Merci pour vos remarques

**Comment by TANK2003** [comment]
La fonction est mise en production :)
