### ISSUE TITLE
Problème sur le calcul des superficies de bâtiment

### ISSUE THREAD

**Issue by aurelienchaumet** [data-osm/frontend#40]
Lorsque la couche "Bâti (tous)" est affichée et que je sélectionne un bâtiment, la surface s'affiche (ce qui est super).

En revanche, la superficie affichée pour les quelques bâtiments que j'ai pu tester (commune de Saint Georges d'Oléron - 17) a l'air d'être doublée.

![Capture d’écran 2020-12-28 à 12 01 07](https://user-images.githubusercontent.com/58778032/103209863-6057dd80-4904-11eb-8dc1-9895878cbe13.png)

La bâtiment sélectionné ici (ici https://www.openstreetmap.org/#map=18/45.97534/-1.32920) affiche une surface de 453,12m2, alors qu'il fait plutôt aux alentours des 210m2.

Ce bâtiment possède un étage, mais j'ai réalisé le même test sur des rez-de-chaussée et l'erreur a l'air d'être la même.

**Comment by TANK2003** [comment]
Merci du retour.
Ceci est lié à la projection. Par défault la BD se mettait en 3857, je relance la BD en 2154. on devrait avoir un résultat en semaine.

**Comment by TANK2003** [comment]
resolut
