### ISSUE TITLE
inclure les shop=wine dans la rubrique Alcools

### ISSUE THREAD

**Issue by zorglubu** [data-osm/frontend#43]
Bonjour,
Les shop=alcohol sont bien affichés dans la rubrique "Alcools", mais, sauf erreur, les shop=wine ne sont nulle part.
Il n'est peut-être pas utile de créer une nouvelle rubrique, et les ajouter à la requête alcools pourraît être suffisant.
Merci :-)

**Comment by JLZIMMERMANN** [comment]
Fait, merci de la remontée
