### ISSUE TITLE
Les labels sont par dessus des icônes

### ISSUE THREAD

**Issue by overflorian** [data-osm/frontend#47]
Je suggère de corriger ce problème d'ergonomie :
![image](https://user-images.githubusercontent.com/11553211/108481293-51ecc900-7298-11eb-985f-ed94cd02f9be.png)
Testé avec la dernière version de Mozilla Firefox sous Ubuntu.

**Comment by overflorian** [comment]
Bonjour, le problème est bien corrigé sur desktop mais pas sur mobile.
Configuration : firefox mobile, dernière version pour Android.

J'ai également testé sur Chrome, c'est pire : rien n’apparaît :
![Screenshot_20211128-114535](https://user-images.githubusercontent.com/11553211/143764667-7495037b-e3e8-45a2-9d9b-5f01a32ef38d.jpg)

**Comment by TANK2003** [comment]
Oui, pour l'instant j'ai pas encore bosse le cote mobile vraiment.
