### ISSUE TITLE
Mapillary : navigation dans photo

### ISSUE THREAD

**Issue by JLZIMMERMANN** [data-osm/frontend#5]
Dans la popup en cliquant sur l'objet une photo Mapillary peut s'afficher.
**Exemple de l'objet :** http://demo.openstreetmap.fr//map?feature=couche,393,48,538578.1785661641,5485182.485287932,7435107623

**Résultat :** Si on clique sur la photo une fenêtre s'ouvre avec la vignette Mapillary appelée sur le serveur.
**Attendu :** activer une URL permettant la navigation dans l'image

**Comment by TANK2003** [comment]
resolut
