### ISSUE TITLE
(feature) Conseiller une couche quand on en choisit une

### ISSUE THREAD

**Issue by datagistips** [data-osm/frontend#51]
Par exemple, conseiller les parkings quand on affiche les sentiers de randonnée.

**Comment by rxlacroix** [comment]
Ou par mot clé proposer un ensemble de couches directement exemple : 

Mot clé : rando
Couches : sentiers de rando + panneaux d'orientation + parkings + sommets + cols ...

**Comment by TANK2003** [comment]
resolut : système de mots clés ajouté
