### ISSUE TITLE
Limitation de vitesse

### ISSUE THREAD

**Issue by SylvainH59** [data-osm/frontend#57]
Lorsqu'on affiche les données relatives aux limitations de vitesse, on a aussi bien les routes que les voies ferrées.
Ne faudrait-il pas rajouter également un filtre highway=* ?

**Comment by pascalpvk** [comment]
Je confirme que le filtre "Route 130", par exemple, peut générer des erreurs. Sur la capture jointe (région parisienne, sud de versaille), on observe un élément tagué "detail:track" qui se trouve être une voie de chemin de fer avec un maxspeed et non pas une route. D'une manière générale, l'outil data-osm est excellent. Je rajouterai une information sur les filtres (Que signifie par exemple "Route à 130km/h" en terme d'attibuts OSM
![Data_OSM](https://user-images.githubusercontent.com/5699220/143764448-77129da9-1c94-4934-a16d-ed4a32d4e697.png)
)

Cf https://www.openstreetmap.org/edit#map=19/48.79409/2.11183

detail=track
electrified=contact_line
frequency=0
gauge=1435
importance=regional
maxspeed=130
operator=SNCF Réseau
passenger_lines=4
railway=rail
railway:track_ref=2bis
ref=420000
ref:FR:SNCF_Reseau=420000,1,V2BIS,1.154,32.514
source=Bing
usage=main
voltage=1500

**Comment by JLZIMMERMANN** [comment]
Bonjour,
Merci de l'observation, j'ai affiné la requête en réduisant la requête uniquement à la voirie.

**Comment by pascalpvk** [comment]
Cela a bien résolu le problème des railway, merci
