### ISSUE TITLE
écran d'accueil : date de mise à jour du serveur

### ISSUE THREAD

**Issue by JLZIMMERMANN** [data-osm/frontend#6]
**Situation :** écran d'accueil sans affichage de la date de mise à jour de la donnée.

**Attendu :** afficher la date pour permettre de savoir si les modifications faites dans OSM ont été prises en compte.

**Comment by TANK2003** [comment]
Intégrer la date MAJ dans les attributions du menu de téléchargement

**Comment by TANK2003** [comment]
Egalement dans les attributions de la carte en bas a droite
