### ISSUE TITLE
Valeur de la puissance du générateur électrique masquée par le libellé 

### ISSUE THREAD

**Issue by lca000** [data-osm/frontend#67]
Carte des réseaux d'énergie électrique
Lorsque l'on clique sur l'icône d'un générateur les données relatives à ce générateur s'affichent dans une fenêtre de type popup.
Le problème est que la puissance du générateur électrique est masquée.
Exemple :
A la centrale électrique de Cordemais ( 44 Loire Atlantique) :
Le libellé generator:output:electricity : masque la puissance du générateur qui je pense doit être de 600 MW
Le problème existe quelque soit le navigateur que j'ai essayé (Firefox, edge, brave) sur PC sous Windows. 
Le problème existe ausssi sur tablette android.
Le problème existe quelque soit le type de générateur (Solaire éolien ou charbon etc.).
Peut-être que le libellé generator:output:electricity est trop long ou contient un : de trop ? 
![Capture](https://user-images.githubusercontent.com/89643127/131127211-bdd8df6f-4dbf-4e23-b5d0-33803027c2cd.PNG)

**Comment by TANK2003** [comment]
resolut

Merci pour les retours !
