### ISSUE TITLE
Ambiguité Laverie (linge) et Station de lavage (voiture

### ISSUE THREAD

**Issue by nuxper** [data-osm/frontend#7]
Actuellement la couche "Laverie" avec icone représentant une Laverie pour le linge est configurée avec le filtre amenity=car_wash . Ce filtre correspondrait plutot à une Station de lavage de voiture.

Étrangement le filtre shop = laundry or shop=dry_cleaning qui correspondrait à "Laverie ou Pressing" est lui dans le filtre correspondant à "Pressing"

![image](https://user-images.githubusercontent.com/7891262/94493561-3996e780-01ed-11eb-97a3-ed65be548a68.png)

**Comment by TANK2003** [comment]
Merci, j'ai modifié le l’icône. Le lien de la couche : http://demo.openstreetmap.fr//map?layers=couche,337,36

<img width="277" alt="Screenshot 2020-10-12 at 20 54 28" src="https://user-images.githubusercontent.com/49986468/95780958-2b58c900-0ccd-11eb-9cee-2e16af44eda5.png">

**Comment by nuxper** [comment]
Merci @TANK2003 !

Je pense cependant que le terme "Laverie" devrait également être modifié. "Laverie" signifie "Blanchisserie dans laquelle le linge de chaque client est lavé séparément, dans des machines individuelles." (voir https://www.larousse.fr/dictionnaires/francais/laverie/46473 )

Si "Station de lavage de voiture" est trop long, je suggère au moins d'utiliser plutot "Lavage auto" ou "Lave-auto", qu'en penses-tu ?

**Comment by TANK2003** [comment]
De rien, effectivement Lavage auto ca mieux. Ca a été mise à jour.

Merci encore !
