### ISSUE TITLE
Fournir une couche "Route sans limitation de vitesse"

### ISSUE THREAD

**Issue by pascalpvk** [data-osm/frontend#86]
Nous avons déjà les 6 couches "Route (limitées) à (30|50|80|90|110|130).
Il serait intéressant de fournir la couche "Route sans vitesse limite indiquée".
Et pourquoi pas aussi une couche comprenant toutes les routes (highway=*)

**Comment by TANK2003** [comment]
Avoir une couche toutes les routes, est très très lourde. Notre Infra actuelle ne la supportera pas malheureusement. Idem pour toutes les routes sans limitations
