### ISSUE TITLE
Boutton pour editer les donnees OSM

### ISSUE THREAD

**Issue by TANK2003** [data-osm/frontend#90]
A la fois sur JOSM, ID, et autres, regarder ce qui exister pour ca

**Comment by caillou15** [comment]
Je viens d'avoir l'idée aussi, c'est vrai que ça manque.

**Comment by TANK2003** [comment]
C'est fait. 

<img width="351" alt="image" src="https://user-images.githubusercontent.com/49986468/161439094-b7e0d0a9-4731-4328-b234-ddc7dbb9447e.png">

Merci pour votre contribution !
